# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.LEDONBTN = QtWidgets.QPushButton(Dialog)
        self.LEDONBTN.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.LEDONBTN.setObjectName("LEDONBTN")
        self.GREEN_LED = QtWidgets.QLabel(Dialog)
        self.GREEN_LED.setGeometry(QtCore.QRect(150, 40, 80, 73))
        self.GREEN_LED.setText("")
        self.GREEN_LED.setObjectName("GREEN_LED")
        self.LEDOFFBTN = QtWidgets.QPushButton(Dialog)
        self.LEDOFFBTN.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.LEDOFFBTN.setObjectName("LEDOFFBTN")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LEDONBTN.setText(_translate("Dialog", "LEDON"))
        self.LEDOFFBTN.setText(_translate("Dialog", "LEDOFF"))
